### PR TITLE
fix: allow cypress@v7 in peer dependency range

### PR DESCRIPTION
**Pull request by SimenB**
**What**:

To not have a peer dep warning when installing

**Why**:

https://github.com/cypress-io/cypress/releases/tag/v7.0.0

**How**:

GH Editor

**Checklist**:

- [ ] Documentation
- [ ] Tests
- [x] Ready to be merged

### CODE REVIEW

**Comment by JeremyGrieshop** [comment]
NPM7 currently blocks installing cypress@7.x unless you use the `--legacy-peer-deps` option, so this is a requirement for that, I believe.

**Review by wbulaszenko — APPROVED** [review]

**Comment by SimenB** [comment]
@nickmccurdy ping 🙂

**Comment by alexkrolick** [comment]
image

CI is failing for some reason

**Comment by SimenB** [comment]
Yeah, it seemed super transient, so I didn't bother. Retriggering seems to have fixed it 👍

**Comment by joelgrimberg** [comment]
so how long will it take to be released? can't wait :)

thanks to all of you for taking the effort!

**Comment by alexkrolick** [comment]
Sorry, walked away after re-triggering. Looks like release worked fine.

**Pull request merged**
