### PR TITLE
Ensure higher version of dom is used

### PR DESCRIPTION
**Pull request by weyert**
Updated the package version of @testing-library/dom

**What**:

Increased the minimum version of the @testing-library/dom dependency for the project

**Why**:

To ensure we Cypress related fixes for setImmediate are included when being used

**How**:

Updated package.json

**Checklist**:

- [ ] Documentation
- [ ] Tests
- [X] Ready to be merged

### CODE REVIEW

**Comment by kentcdodds** [comment]
I'm hoping the build issue is a fluke. Thanks for the PR!

**Comment by kentcdodds** [comment]
@all-contributors please add @weyert for code

**Comment by weyert** [comment]
Any chance we could do a release? Then I revert my pinned resolutions in package.json for cypress :)

**Comment by kentcdodds** [comment]
If it's not releasing, it's because the build is broken. I'm out with family right now. Care to take a look?

**Comment by weyert** [comment]
`The cypress npm package is installed, but the Cypress binary is missing.` is being returned how can trigger a new build? Seems like CI issue to me. Can't imagine increasing `@testing-library/dom` package version should cause this.

**Comment by kentcdodds** [comment]
Yeah, I have no idea what it is and I don't have the bandwidth to look into it right now. Sorry :-(

**Comment by weyert** [comment]
Thank you!

**Pull request merged**
