### PR TITLE
Reintroduce timeout on the outer command then chain

### LINKED ISSUE #89: All(?) timeouts report as "cy.then() timed out after waiting '4000ms'" rather than printing actual expectation failure
- `cypress-testing-library` version: 5.0.1
- `node` version: 12.6.0
- `npm` (or `yarn`) version: 1.17.3

Since upgrading to 5.0.1, it seems any timeouts are all being reported as `Your callback function returned a promise which never resolved`.

Any expectation that times out now just prints out the below, which obviously makes it pretty difficult to know which assertion it's actually failing on.

```
     CypressError: cy.then() timed out after waiting '4000ms'.

Your callback function returned a promise which never resolved.

The callback function was:

thenArgs => {
        const getValue = () => {
          const value = commandImpl(thenArgs.document);
          const result = Cypress.$(value); // Overriding the selector of the jquery object because it's displayed in the long message of .should('exist') failure message
          // Hopefully it makes it clearer, because I find the normal response of "Expected to find element '', but never found it" confusing

          result.selector = `${queryName}(${queryArgument(args)})`;

          if (result.length > 0) {
            consoleProps.yielded = result.toArray();
          }

          return result;
        };

        const resolveValue = () => {
          // retry calling "getValue" until following assertions pass or this command times out
          return Cypress.Promise.try(getValue).then(value => {
            return cy.verifyUpcomingAssertions(value, waitOptions, {
              onRetry: resolveValue
            });
          });
        };

        if (queryRegex.test(queryName)) {
          // For get* queries, do not retry
          return getValue();
        }

        return resolveValue().then(subject => {
          // Remove the error that occurred because it is irrelevant now
          if (consoleProps.error) {
            delete consoleProps.error;
          }

          return subject;
        });
      }
 ```

### PR DESCRIPTION
**Pull request by jagregory**
**What**:

Fixes #89 and maybe #37 

**Why**:

There was a regression in ab5263d that removed the timeout from the promise chain.

**How**:

I reintroduced the timeout.

**Checklist**:

- [ ] Documentation
- [ ] Tests
- [x] Ready to be merged

### CODE REVIEW

**Comment by kentcdodds** [comment]
cc @Jmaharman

**Comment by bdelaforest** [comment]
@kentcdodds do you think we can have this merged soon? It's really annoying not to be able to override the default `timeout` value… 😕

**Comment by jagregory** [comment]
If it’s any reassurance to the maintainers, I’ve been using my PR for a couple of weeks now with no issues. Getting this merged would be great 😊

**Comment by kentcdodds** [comment]
That is very encouraging @jagregory! Thank you.

**Pull request merged**
