### PR TITLE
fix: remove deprecated cy.state('subject')

### PR DESCRIPTION
**Pull request by warpdesign**
**What**:

Replace `cy.state('subject')` by `cy.currentSubject()`.

**Why**:

`cy.state('subject')` is being deprecated:

image

**How**:

Replace `cy.state('subject')` by `cy.currentSubject()` in `utils.ts`.

**Checklist**:

- [ ] Documentation N/A
- [x] Tests
- [x] Ready to be merged

### CODE REVIEW

**Review by IP-Erin — COMMENTED** [review]
I appreciate the clean up here. Curious about cy.within - would this need to be reviewed/updated too?

**Comment by skvale** [comment]
Linking the PR that deprecated this: https://github.com/cypress-io/cypress/pull/23092

> While we would normally consider internal state to be internal, cypress-testing-library relies on cy.state('subject'). Therefore, this PR includes a shim to keep that call working as before. Once this PR is released, we will follow up with them to move over to the new call, ensuring that no end users (with or without cypress-testing-library) ever experience disruption (beyond the console warning).

**Comment by TylorMayfield** [comment]
image
My console appreciates it

**Review by NicholasBoll — APPROVED** [review]

**Review by marctorrelles — APPROVED** [review]

**Comment by olaj** [comment]
It would be awesome if this gets merged, if it works that is.

**Comment by NicholasBoll** [comment]
Duplicate of #233

**Pull request closed without merging**
