### PR TITLE
Fix configureCypressTestingLibrary typings

### LINKED ISSUE #143: Property 'configureCypressTestingLibrary' does not exist on type 'cy & EventEmitter'
- `cypress-testing-library` version: 6.0.0
- `node` version: 10.18.1
- `npm` (or `yarn`) version: npm v6.13.4

Relevant code or config

FWIW I tried installing `@types/testing-library__cypress` v5.0.6 (even though it was already in `node_modules`). 
Here's my `tsconfig.json`:

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "allowJs": true,
    "checkJs": false,
    "baseUrl": "../node_modules",
    "outDir": "./ConvertedJSFiles",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "types": [
      "cypress",
      "@types/testing-library__cypress"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  },
  "include": [
    "**/*.*"
  ],
  "exclude": [
    "node_modules",
    "cache"
  ]
}
```

What you did:

I enabled javascript checking via `checkJs` in `tsconfig.json` and invoked `cy.configureCypressTestingLibrary` in `cypress/support/index.js`

What happened:

Typescript is telling me `Property 'configureCypressTestingLibrary' does not exist on type 'cy & EventEmitter'.`

Many of my custom commands weren't recognized as being members of `Cypress.Chainable` and adding their definitions to `commands.d.ts` fixed it, and now `configureCypressTestingLibrary` is the only one giving me trouble. It looks like it's because it's missing from the type definitions.

### PR DESCRIPTION
**Pull request by Thisen**
**What**:

Fixes `cy.configureCypressTestingLibrary(config)` for TypeScript users. Fixes #143.
Also, ran `prettier` for the changed files.

**Why**:

Type safety. 🎉

**How**:

I've added a declaration for `configureCypressTestingLibrary` in the type definitions.

**Checklist**:

- [X] Documentation
- [X] Tests
- [X] Ready to be merged

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
Thank you!

**Comment by kentcdodds** [comment]
@all-contributors please add @Thisen for code

**Comment by kentcdodds** [comment]
@all-contributors please add @Thisen for code and tests

**Comment by Thisen** [comment]
Always happy to help. 👏

**Pull request merged**
