### PR TITLE
feat: allowed cypress v4 as a valid peer

### LINKED ISSUE #118: support for cypress v4
- `cypress-testing-library` version: `v5.2.1`
- `node` version: `v10.19.0`
- `npm` (or `yarn`) version: `v6.13.4`

Relevant code or config

https://github.com/testing-library/cypress-testing-library/blob/5664b09a01f49c33998111e37dbab48b4283f28e/package.json#L54

What you did:

installed `v4.0.0` of cypress and ran `npm ls`

What happened:

slightly different versions in this project, but was the first i found with public logs: https://travis-ci.com/travi-org/theme-components/builds/147829710#L301-L313

Reproduction repository:

https://github.com/travi-org/theme-components/pull/4

Problem description:

the peer ranges defined as compatible for cypress do not include `v4.0.0` that was released today: https://docs.cypress.io/guides/references/changelog.html#4-0-0

Suggested solution:

add `^4.0.0` to the allowed peer ranges:

```js
"cypress": "^2.1.0 || ^3.0.0" 
```

### PR DESCRIPTION
**Pull request by travi**
closes #118

**Checklist**:

- [ ] Documentation
- [ ] Tests
- [x] Ready to be merged

### CODE REVIEW

**Comment by NicholasBoll** [comment]
@travi Could you also update `devDependencies` to `^4.0.0`? If the CI tests pass, I think this library can officially support Cypress@2,3,4

**Comment by travi** [comment]
sure thing

**Comment by travi** [comment]
updated

**Comment by NicholasBoll** [comment]
@all-contributors please add @travi for code

**Pull request merged**
