### PR TITLE
Update Cypress peer dependency to 13

### PR DESCRIPTION
**Pull request by marktnoonan**
Hi! Let me know if you want to wait until closer to release to merge this, I just wanted to flag that 13 is coming, I do not have a definitive release date. I have seen no problems with Testing Library in the pre-release of the new version and there's nothing that seems like it would cause a problem. Just wanted to let you know that a new major is coming soon-ish.

**What**:

Cypress 13 is coming soon, it will include some breaking changes to Cypress but nothing that breaks Cypress Testing Library.

**Why**:
Avoid peer dependency warnings when people upgrade.

**How**:

**Checklist**:

- [ ] Documentation
- [ ] Tests
- [x] Ready to be merged

### CODE REVIEW

**Review by davereid — APPROVED** [review]
LGTM

**Comment by nrutman** [comment]
@NicholasBoll any thoughts on getting this merged by the team? It's blocking upgrades to Cypress 13 for anyone who uses Cypress Testing Library.

**Review by fizz3rworkday — APPROVED** [review]

**Comment by Lasidar** [comment]
We are waiting on this fix as well for our upgrade to Cypress 13

**Review by PuckmanXY — APPROVED** [review]

**Review by Guilherme-Farias — APPROVED** [review]

**Comment by vicwomg** [comment]
Note that if you're running into issues with cypress-io/github-action , you can temporarily work around it by overriding the install command in the workflow file to ignore peer deps:

```
- name: Cypress e2e run
        id: cypress_e2e_run
        uses: cypress-io/github-action@v6.4.0
        with:
          # Override install because Cypress upgrades break peer deps of other packages
          **install-command: npm ci --legacy-peer-deps**
          install: true
          browser: chrome
          # `Record: true` sends results to Cypress Dashboard
          record: true
          parallel: true
```

**Comment by istr** [comment]
For the time being, you might as well override the peer dependency in your root `package.json`. Minimal working example:

```json
{
  "devDependencies": {
    "@testing-library/cypress": "9.0.0",
    "cypress": "13.1.0"
  },
  "overrides": {
    "@testing-library/cypress": {
      "cypress": "^13.0.0"
    }
  }
}
```

Dependency tree:

```bash
npm list
cyp-test-foo@ /home/istr/cyp-test-foo
├── @testing-library/cypress@9.0.0 overridden
└── cypress@13.1.0 overridden
```

**Review by nghoiying04 — APPROVED** [review]

**Comment by ray-peters** [comment]
Hey team, any blockers on this front? Is there anything we can do to help move this update along?

**Comment by PowerSupply** [comment]
Is this moving forwards?

**Comment by nrutman** [comment]
@NicholasBoll @kentcdodds  is anything holding this up from being merged? It's preventing people from upgrading to Cypress 13 if they use your package.

**Review by kentcdodds — APPROVED** [review]

**Comment by nrutman** [comment]
Thank you @kentcdodds!!

**Comment by Kocal** [comment]
Thanks for merging :)

**Pull request merged**
